# -*- coding: utf-8 -*-
"""mod1_class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veCpsVODSe9NTGEN7__ZrmAA3chatQAK
"""

distance_to_home= int(input("Enter distance"))
fuel_efficiency=float(input("Enter fuel efficiency"))
print("Fuel needed:",int(distance_to_home*fuel_efficiency))

result=100-20 / (4 *5)
int(result)

asteroid_sizes=[34,45,6,84,81,68,86]
smallest= min(asteroid_sizes)
largest=max(asteroid_sizes)
print("smallest asteroid: ",smallest)
print("largest asteroid: ",largest)

base=3
exponent=4
power_value= pow(base, exponent)
power_value
power= base**exponent
power

import math
i=0.254
x=52435
print(math.ceil(i*x))

tweet="Hello earth Antor from sector 69"
print(tweet[])

messy="hi# my name is ##richmond"
cleaned = messy.replace('#','')
print(cleaned)
print(cleaned.upper())

planet="earth"
temp= 22.5678
weather= "rainy"
report ="planet: {}, temp: {:.1f}, weather: {}".format(planet,temp,weather)
print(report)
mass =77
print(f"my mass {mass} kg")
print(f"{mass} {planet} {weather}")

donut =["glazed","chocolate","galactic", "nut"]

#for donuts in donut:
    #print(donuts)


angle=0
#while angle<90:
  # print("Angle:",angle)
  # angle=angle+30
i=4
for i in range (10,3,-1):
  print(i)

from typing_extensions import Protocol
Protocols= ["ok", "ok", "bad", "ok", "yo", "good", "nice"]
for i, Protocol in enumerate(Protocols):
  if Protocols=="bad":
    continue
    print(i,Protocol)